### ISSUE TITLE
bug in admin when constance is saved

### ISSUE THREAD

**Issue by alex1989** [jezdez/django-constance#100]
I have found in django admin, when you save constance of project, I have all time form.is_valid() is False. Although I check function clean_version it's not call, I think problem when start init fields in ```__init__``` method, with different types, and there is error, when we call form.is_valid(). I think need review all form fields and check it. My problem happens when I have only int type in CONSTANCE_CONFIG dictionary.

**Comment by alex1989** [comment]
I just check form errors and error is "version field is required field"

**Comment by alex1989** [comment]
It's problem happens in django-grapelli

**Comment by YuriHeupa** [comment]
Why this issue was closed? it was solved? i've the same problem
