### ISSUE TITLE
How can i store list/tuple object in constance

### ISSUE THREAD

**Issue by kuldeeprishi** [jezdez/django-constance#105]
I need to store a list of keys which i can change dynamically, but i guess constance doesn't support storing list/tuple objects. any workaround

**Comment by ad-m** [comment]
```python
print config.TAGS.split(';')
```

**Comment by kuldeeprishi** [comment]
Ok thanks, i tried eval :) thats works even for storing dict objects also

**Comment by ad-m** [comment]
I use json to store some constance' data too.

**Comment by jezdez** [comment]
Yeah, for now iterables are out of scope of this. JSON works fine indeed.

**Comment by NiranjanSingh** [comment]
@ad-m  Hey, Is it possible to store dictionary there using json, and how to retrieve values of them. I want it to be editable from admin interface, Is there any way we can provide custom fields? Thanks
