### ISSUE TITLE
An example of using without close relationship

### ISSUE THREAD

**Issue by ad-m** [jezdez/django-constance#106]
I am suggest add to docs example of use django-constance without strict relation with support in settings or not, without extending app requirements:
```python
# app/utils.py
from django.conf import settings

try:
    from constance import config

    def get_settings(x):
        return getattr(config, x) if hasattr(config, x) else getattr(settings, x)
except ImportError:
    def get_settings(x):
        return getattr(settings, x)
```
Now you can overwrite settings by django-constance, but you don't have use it, so your app will be more reusable.

**Comment by ad-m** [comment]
@jezdez , what do you think about build it into django-constance? I mean silently pass (extra settings?) to django.conf.settings like ```return getattr(config, x) if hasattr(config, x) else getattr(settings, x)```.

Then everybody will use in own app in very plugable way. It will be something like:
```python

try:
    from constance import config as settings
except ImportError:
    from django.conf import settings
```

**Comment by jezdez** [comment]
Nope, constance solves a different problem than the settings, so this would be a terrible idea to promote. Don't do this. You've been warned.
