### ISSUE TITLE
Support the Django sites framework

### ISSUE THREAD

**Issue by leesolway** [jezdez/django-constance#107]
Feature request

Global settings are needed and very helpful however i have found use cases for specific site configuration. Would it be possible to build in support for the Django contrib sites framework?

**Comment by camilonova** [comment]
Maybe you can have that changing the prefix, like:

```python
CONSTANCE_REDIS_PREFIX = 'constance:{0}:'.format(SITE_ID)
```

**Comment by leesolway** [comment]
It's possible but i believe that would leave two issues..

1. Admin integration - One site (domain) can be used to edit another via the admin
2. It would break the database backend compatibility

**Comment by camilonova** [comment]
You're right.

**Comment by jezdez** [comment]
This is out of scope of the app, sorry.
