### ISSUE TITLE
Google DMCA takedown notice

### ISSUE THREAD

**Issue by jasonlttl** [jezdez/django-constance#89]
As an FYI, "Takedown Piracy LLC" sent a DMCA takedown notice for this repository to google on Dec 24th.

The notice is posted at chilling effects...
https://www.chillingeffects.org/notices/10281020

and less exactly on google's transparency site (doesn't list exact github urls)
http://www.google.com/transparencyreport/removals/copyright/requests/1763826/

There's an article describing this problem here which made slashdot.
http://motherboard.vice.com/read/porn-companies-are-going-after-github

I just happened to notice and thought you might want to know.

**Comment by nemesisdesign** [comment]
First they came for porn...

LOL

**Comment by jezdez** [comment]
WHAT. THE. FUCK.

**Comment by aleszoulek** [comment]
WOW.

Is there a way to release that?

**Comment by jezdez** [comment]
@aleszoulek Yeah, there is a complaint form, I'm going to fill it out.

**Comment by aleszoulek** [comment]
@jezdez thanks man!

**Comment by jezdez** [comment]
Wait, I won't, this will only cost money. This is about this movie: http://en.wikipedia.org/wiki/Constance_%281998_film%29

**Comment by nemesisdesign** [comment]
shaming them publicly on twitter also works well

**Comment by jezdez** [comment]
I suggest to rename the repo and move on. Don't want to pay their lawyer even a dime.

**Comment by nemesisdesign** [comment]
come on, seriously? This is neither a movie not commercial product.

**Comment by aleszoulek** [comment]
I have no words...

Renaming may be the only option, but I hate to conform to this stupidity.

Also lol on searching for codename never used in a porn movie :)

**Comment by jezdez** [comment]
@aleszoulek Me neither, what a waste of time. Any suggestions for the name?

**Comment by aleszoulek** [comment]
@jezdez ``django-konstance`` ?

Let's give it more thought tho. Are we just talking about the repo and keeping the package name, pypi, readthedocs etc the same?

**Comment by nemesisdesign** [comment]
You are not obliged to do this. They are probably thinking this repo has materials of their stupid movie. Why rename the project and change the package name giving annoyances to hundreds maybe thousands of developers for a stupid porn movie?

**Comment by jasonlttl** [comment]
If a company can send takedown notices with 4000 urls to google resulting in removal of data from google without proper checks, that sounds like security problem in Google's search product. Maybe you could report it (ironically) to google's vulnerability bounty program. That would probably get more attention than going through regular channels while making a point of sorts.

**Comment by aleszoulek** [comment]
Or we can setup ``django-constance.github.com`` page redirecting to this repo. Or what ever to atleast still apear in "django constance github" querries.

**Comment by nemesisdesign** [comment]
https://support.google.com/youtube/answer/2807684?hl=en

**Comment by nemesisdesign** [comment]
ounter notification

The administrator of an affected site or the provider of affected content may make a counter notification pursuant to sections 512(g)(2) and (3) of the Digital Millennium Copyright Act. When we receive a counter notification, we may reinstate the material in question.

Please click on the relevant link below if you would like to file a counter notice for one of the following products:

Blogger
Web Search
Google+ Pages/Profiles
If your issue relates to a product not listed above, please find it on our legal troubleshooter and choose the “Counter Notice” option. Please note that you will be liable for damages (including costs and attorneys' fees) if you materially misrepresent that a product or activity is not infringing the copyrights of others. Accordingly, if you are not sure whether certain material infringes the copyrights of others, we suggest that you first contact an attorney. A sample counter notification may be found at http://www.chillingeffects.org/dmca/counter512.pdf.

When filling out our counter notice form, please be sure to identify the specific URLs or other unique identifying information of material that Google has removed or to which Google has disabled access.

**Comment by jezdez** [comment]
@nemesisdesign Thanks for your advise, I already looked through Google's documentation to complain about a DMCA notice. It'll mean they forward the counter notifications to the sender, which means to a lawyer that sent the notice on behalf of the copyright owner. In other words, this will result in legal interaction which I'm simply not interested time and money wise.

@aleszoulek I'll thing about something, locking this issue for now to not make things worse.

**Comment by jezdez** [comment]
@aleszoulek So how about renaming it to django-constants?

- [ ] I'd rename the GitHub project and GitHub will redirect automatically
- [ ] I'd rename the readthedocs project or add a new project there and redirect from the old one (I believe this is possible)
- [ ] I would add a notice to the frontpage of the documentation (also `README.rst`) to state the fact that the project was renamed because of a legal threat that the maintainers are not capable to fight
- [ ] I'm afraid I'll need to re-upload all the version packages to PyPI since the tarball name is important to pip etc. The old PyPI page would get the same notice as added to the new repo
- [ ] I'll send a mail to all fork owners to inform them of the above steps

Is there anything that I missed?

**Comment by aleszoulek** [comment]
@jezdez Two questions: 
1) Will the GH's redirect somehow work for git repository URL, or would that break all requirements (and basicaly git clones) that are made against the current git repo?  Would you like to rename also the pypi package? Or just change the metadata there?
2) Most importantly, I'm still not 100 % sure it is worth it. Having to rename project, repo, possibly break other people dependecies VS having ungoogle-able github page, but perfectly googlable pypi, readthedocs etc (which can take the devs to the github repo by single click..).

**Comment by jezdez** [comment]
So yeah, I had multiple people send me mails about it and asked me not to rename the project. One person pointed at the fact that the django-constance GitHub page shows up in Google search results again (as of the date of this comment) and the DMCA notice at the bottom of the Google search result page was removed.

Additionally the Google transparency page now includes a series of GitHub URLs (including django-constance's) under the "no action taken" column: http://www.google.com/transparencyreport/removals/copyright/requests/1763826/

So I'm closing this as "wontfix" (read: "wtf").

**Comment by aleszoulek** [comment]
Ah. What a wonderfuly wasted time and resources. Happy it's resolved, but still, "wtf"?

Thanks for investing so much efford into this.
