### ISSUE TITLE
Choice field?

### ISSUE THREAD

**Issue by dpetzel** [jezdez/django-constance#91]
Just stumbled across this library today, this is exactly what I went in search of, thanks for releasing this.

I'm stilling getting ramped up so apologies if this was covered, but I couldn't find it. I see you support different data types, and render accordingly in the Admin (awesome!!). I was hoping to setup on of my configuration options as a choice, allowing someone to pick one value from a list of choices (as opposed to a text box where they might typo it). Is this possible? If not no biggie, I can work around it, but would be awesome if it was there already.

Thanks

**Comment by bufke** [comment]
This was discussed here https://github.com/jezdez/django-constance/issues/63

**Comment by dpetzel** [comment]
@bufke, Thanks sounds like the answer to `Is this possible?` is nope (at least not currently). Thanks for confirming.
