### ISSUE TITLE
Django 1.8 ContentType Model change

### ISSUE THREAD

**Issue by jonzlin95** [jezdez/django-constance#93]
Hi all,

Love constance, and I've been using on my projects for a while now. I've been playing around with the dev version of Django (1.8a1/1.8b1), and noticed a change in the ContentTypes Model that breaks Constance on manage.py migrate.

```
https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/
name
The human-readable name of the content type. This is taken from the verbose_name attribute of the model.
Changed in Django 1.8:
Before Django 1.8, the name property was a real field on the ContentType model.
```

In particular, the error is 

```
File "/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1369, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'name' into field. Choices are: app_label, id, logentry, model, permission
```

from 

```
File "/lib/python2.7/site-packages/constance/models.py", line 16, in create_perm
    model='config')
```

I was able to hack around it simply by removing the name='config' line from constance/models.py
Thanks for all the hard work!

Cheers,
Jonathan

**Comment by jarieb** [comment]
I ran into the same thing and removing name='config' fixed it as well.

**Comment by jonzlin95** [comment]
See #96
