### ISSUE TITLE
Can we have validations?

### ISSUE THREAD

**Issue by camilonova** [jezdez/django-constance#99]
For example if you need to validate a range in a setting, we should be able to add a validation before the setting is saved.

@jezdez what do you think?

**Comment by jezdez** [comment]
Hm, sounds like it would make things horribly complicated and the settings a lot more verbose. I'm -1 on this idea.

**Comment by camilonova** [comment]
@jezdez how would be a good approach to solve this outside constance?

**Comment by jezdez** [comment]
I don't know, sorry.
